name: coverage-reporter action

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    uses: ziishaned/jest-reporter-action@v0.0.1
    with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        test-command: "npx jest --coverage"